### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by akh33l** [0904-mansi/Face-recognition-Challenge-Engage-22#1]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from facerec import *
  File "/home/akheel/Downloads/Face-recognition-Challenge-Engage-22-main/facerec.py", line 82, in <module>
    train_model()
  File "/home/akheel/Downloads/Face-recognition-Challenge-Engage-22-main/facerec.py", line 43, in train_model
    model.train(images,lables)
cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/opencv_contrib-3.4.2/modules/face/src/lbph_faces.cpp:265: error: (-213:The function/feature is not implemented) Using Original Local Binary Patterns for feature extraction only works on single-channel images (given 16). Please pass the image data as a grayscale image! in function 'elbp'

**Comment by 0904-mansi** [comment]
> Traceback (most recent call last): File "main.py", line 11, in from facerec import * File "/home/akheel/Downloads/Face-recognition-Challenge-Engage-22-main/facerec.py", line 82, in train_model() File "/home/akheel/Downloads/Face-recognition-Challenge-Engage-22-main/facerec.py", line 43, in train_model model.train(images,lables) cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/opencv_contrib-3.4.2/modules/face/src/lbph_faces.cpp:265: error: (-213:The function/feature is not implemented) Using Original Local Binary Patterns for feature extraction only works on single-channel images (given 16). Please pass the image data as a grayscale image! in function 'elbp'

Hey @akh33l there is an issue with filenames I removed some unnecessary files from my repo. you can comment on those imports and for train model you need to register any person so that your face_sample directory will have images as dataset.
